# Generated by Django 3.0.6 on 2020-07-03 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cus_name', models.CharField(max_length=250)),
                ('PE', models.CharField(max_length=250)),
                ('PN', models.CharField(max_length=250)),
                ('Model', models.CharField(max_length=250)),
                ('ICPN', models.CharField(max_length=250)),
                ('ICSpec', models.CharField(max_length=250)),
                ('Part_burn', models.CharField(max_length=250)),
                ('FwVer', models.CharField(max_length=250)),
                ('ICPos', models.CharField(max_length=250)),
                ('CheckSum', models.CharField(max_length=250)),
                ('Prog_name', models.CharField(max_length=250)),
                ('dot_color', models.CharField(max_length=250)),
                ('dot_pos', models.CharField(max_length=250)),
                ('Change_date', models.DateField()),
                ('Fw_note', models.CharField(max_length=250)),
            ],
        ),
    ]
