# Generated by Django 3.0.6 on 2020-07-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdata',
            name='Change_date',
            field=models.CharField(max_length=250),
        ),
    ]
