# Generated by Django 3.0.6 on 2020-07-03 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PE', '0002_auto_20200703_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdata',
            name='Change_date',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='CheckSum',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='Cus_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='FwVer',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='Fw_note',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='ICPN',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='ICPos',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='ICSpec',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='Model',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='PE',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='PN',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='Part_burn',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='Prog_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='dot_color',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='dot_pos',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
