# Generated by Django 3.0.6 on 2020-07-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PE', '0003_auto_20200703_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdata',
            name='dot_pos',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
