# Generated by Django 3.0.6 on 2020-07-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PE', '0004_auto_20200708_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdata',
            name='dot_pos',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
