# Generated by Django 3.0.6 on 2020-07-08 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PE', '0005_auto_20200708_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdata',
            name='dot_pos',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
