# Generated by Django 3.0.6 on 2020-07-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PE', '0007_auto_20200708_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdata',
            name='dot_pos',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
