# Generated by Django 3.0.6 on 2020-07-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PE', '0008_auto_20200709_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdata',
            name='dot_pos',
            field=models.ImageField(upload_to=''),
        ),
    ]
