# Generated by Django 3.0.6 on 2020-07-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PE', '0009_auto_20200709_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdata',
            name='Change_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='dot_pos',
            field=models.ImageField(upload_to='templates/images/'),
        ),
    ]
