# Generated by Django 3.0.6 on 2020-07-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PE', '0011_auto_20200709_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterdata',
            name='Code',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
